augroup VIMRC
	autocmd!
augroup END

" defaults.vim
set list listchars=tab:>-,extends:\\u00bb,precedes:\\u00ab,eol:\\u21b5,nbsp:~

augroup VIMRC
	autocmd BufEnter * execute 'setlocal listchars=tab:>-,extends:\\u00bb,precedes:\\u00ab,eol:\\u21b5,nbsp:~,multispace:┆' . repeat('\ ', &sw - 1)
augroup END
set backspace=start
set number relativenumber

set history=500
set ruler

set showcmd " show currently typed command (as in y)
set wildmenu

" timeout for mapping delay, ttimeout for key code delay
set timeout ttimeout timeoutlen=2000 ttimeoutlen=50

set display=lastline  " defaults.vim sets it to truncate but this seems to make more sense
set scrolloff=2

set hlsearch incsearch

set nrformats-=octal nrformats+=unsigned

set wildmode=longest:list,full

set ignorecase smartcase

set laststatus=2

set splitright splitbelow

nnoremap <silent> <Esc><Esc> :<C-u>nohlsearch<CR>
nnoremap <silent> <F1> <Nop>

if has('termguicolors')
    set termguicolors
endif

augroup MiVLive
	autocmd!
	autocmd BufWritePost .vimrc.yaml call system('miv generate')
	autocmd BufWritePost vimrc.yaml call system('miv generate')
augroup END

" miv
filetype off
if has('vim_starting')
	set rtp^=~/.vim/miv/miv
endif
filetype plugin indent on
syntax enable
