source ~/.vim/base_config.vim
augroup MiVLive
	autocmd!
	autocmd BufWritePost .vimrc.yaml call system('miv generate')
	autocmd BufWritePost vimrc.yaml call system('miv generate')
augroup END

" miv
filetype off
if has('vim_starting')
	set rtp^=~/.vim/miv/miv
endif
filetype plugin indent on
syntax enable
packadd! editorconfig

" vim: set noexpandtab ts=4 sw=4 sts=4 fdm=marker fmr=<<<,>>> :
